[PARSER]
    Name        cri
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   Off

[PARSER]
    Name        book_access
    Format      regex
    Regex       ^\S+ \S+ access method=(?<method>\S+) path=(?<path>\S+) status=(?<status_code>\d+) duration=(?<duration>\S+) remote_addr=(?<client_ip>[0-9.]+):\d+ user_agent="(?<user_agent>[^"]*)"$
    Types       status_code:integer
