[PARSER]
    Name        cri
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name    book_access
    Format  regex
    Regex   ^\S+ \S+ access method=(?<method>\S+) path=(?<path>\S+) status=(?<status>\d+) duration=(?<duration>\S+) remote_addr=(?<remote_addr>[^:]+):(?<remote_port>\d+) user_agent="(?<user_agent>[^"]*)"
